//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Mangement.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library_Mangement.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string Session_TimeOut_Alert_Title {
            get {
                return ResourceManager.GetString("Session_TimeOut_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is expired. Please login again.
        /// </summary>
        internal static string Session_TimeOut_Msg {
            get {
                return ResourceManager.GetString("Session_TimeOut_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is OCLM ?.
        /// </summary>
        internal static string Spash_Title_1 {
            get {
                return ResourceManager.GetString("Spash_Title_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why OCLM?.
        /// </summary>
        internal static string Spash_Title_2 {
            get {
                return ResourceManager.GetString("Spash_Title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Online Library ?.
        /// </summary>
        internal static string Spash_Title_3 {
            get {
                return ResourceManager.GetString("Spash_Title_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The house of knowledge..
        /// </summary>
        internal static string Splash_Summary_1 {
            get {
                return ResourceManager.GetString("Splash_Summary_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We must teach people through books and magazines since books are the entrances to all of our knowledge..
        /// </summary>
        internal static string Splash_Summary_2 {
            get {
                return ResourceManager.GetString("Splash_Summary_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries help you save money and answer questions you didn’t even realize you had!.
        /// </summary>
        internal static string Splash_Summary_3 {
            get {
                return ResourceManager.GetString("Splash_Summary_3", resourceCulture);
            }
        }
    }
}
